"use client"

interface NotesFooterProps {
  notes: string
  terms: string
}

export function NotesFooter({ notes, terms }: NotesFooterProps) {
  return (
    <footer className="border-t border-border pt-6 flex flex-col gap-6">
      {notes && (
        <div className="flex flex-col gap-2">
          <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-widest">
            Notes
          </h3>
          <p className="text-sm text-muted-foreground leading-relaxed">{notes}</p>
        </div>
      )}

      {terms && (
        <div className="flex flex-col gap-2">
          <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-widest">
            Terms &amp; Conditions
          </h3>
          <div className="flex flex-col gap-1">
            {terms.split("\n").map((line, i) => (
              <p key={i} className="text-xs text-muted-foreground leading-relaxed">
                {line}
              </p>
            ))}
          </div>
        </div>
      )}

      <div className="flex items-center justify-between pt-4 border-t border-border">
        <p className="text-xs text-muted-foreground">
          This is a computer-generated quotation and does not require a signature.
        </p>
        <p className="text-xs text-muted-foreground font-medium">
          Generated by{" "}
          <span className="text-primary font-semibold">QuickQuote</span>
        </p>
      </div>
    </footer>
  )
}
